### PR TITLE
fix wrong getCustomImageURL call in getImageGeodata()

### PR DESCRIPTION
**Pull request by citronalco**
Otherwise map won't show because of
"EXCEPTION (0): Call to undefined method Image::getCustomImageURL() in /var/www/html/zenphoto/plugins/zp_openstreetmap.php in line 459"

### CODE REVIEW

**Comment by acrylian** [comment]
Thanks for your contribution. Two comments though:

1. Please explain your issue with `getCustomImage()`. The usage of the image object here is actually correct and intended as using the theme functions would limit this to current image context.

2. Please note that this uses the exif library (called `exifer`)  of Zenphoto itself. So if there is some value read wrong it probably should be fixed there. I cannot test this so this would require your help.

Thanks again.

**Comment by acrylian** [comment]
Thanks for further fixes. But I will still not pull this in before you answer my questions.

`$_zp_current_image` is a global var that is set with the current image object IF we are in current image context. The function passes an image object that is independent on this as the plugin can be used on album pages as well where there is no current image.

**Comment by citronalco** [comment]
1. $image->getCustomImage() did not work at all, at least on my installation (Zenphoto 1.4.14) . All I got was a PHP error:
`EXCEPTION (0): Call to undefined method Image::getCustomImageURL() in /var/www/html/zenphoto/plugins/zp_openstreetmap.php in line 459`
Replacing `$image->getCustomImage()` with `getCustomImage()` as in 
zp-core/zp-extensions/GoogleMap.php's "getGeoCoord" function fixed that.

2.You're probably right with that.

3. After fixing 1 I still had issues with maps with multiple markers on them: In album context there were no thumbnails and no links. In image context there were thumbnails and links, but all from the current image. So again I had a look in GoogleMap.php's "getGeoCoord" function.

**Comment by acrylian** [comment]
1/3. This needs further investigation. `getCustomImageURL` is indeed not an image class method, `getCustomImage` is.  

The plugin class is really meant to be used either in theme context or outside via the object model directly elsewhere. 

Please open a ticket for your issue with a exact description where in what theme this happened. I will try to take a look as soon as I can.

2. Okay, if you can take a look there that would be great. The exif library has a panasonic handler that may need this fix.

I will keep this pull request open for reference but not pull it in.

**Comment by acrylian** [comment]
Apparently forgot to close this…

**Pull request closed without merging**
